### ISSUE TITLE
administrador de dominio no puede ver listado de casillas.

### ISSUE THREAD

**Issue by DavidZbox** [ZBoxApp/manager-react#150]
He creado nuevamente por manager el administrador de dominio zboxadmin@asoex.cl .
Al momento de querer ver el listado de casillas no muestra el listado y la consola indica el siguiente error
```
Error {code: "soap:Receiver", extra: Object}code: "soap:Receiver"extra: Objectcode: "account.TOO_MANY_SEARCH_RESULTS"reason: "number of results exceeded the limit: too many search results returned"trace: "qtp1778535015-150422:https://192.168.0.153:7071/service/admin/soap:1464797182179:697ee0740b7c5550"__proto__: Object__proto__: ObjecthandleError @ client.jsx?e1ca:57(anonymous function) @ client.jsx?e1ca:397(anonymous function) @ zimbra-admin-api.js?d65a:207(anonymous function) @ zimbra-admin-api.js?d65a:2870Request.callback @ zimbra-admin-api.js?d65a:30016(anonymous function) @ zimbra-admin-api.js?d65a:29739Emitter.emit @ zimbra-admin-api.js?d65a:30432xhr.onreadystatechange @ zimbra-admin-api.js?d65a:30098
bluebird.js?5491:1486 Warning: a promise was rejected with a non-error: [object Object]
    at Request.callback (eval at <anonymous> (https://manager.zboxapp.com/678875bundle.js:208:48), <anonymous>:30016:4)
    at Request.eval (eval at <anonymous> (https://manager.zboxapp.com/678875bundle.js:208:48), <anonymous>:29739:11)
    at Request.Emitter.emit (eval at <anonymous> (https://manager.zboxapp.com/678875bundle.js:208:48), <anonymous>:30432:21)
    at XMLHttpRequest.xhr.onreadystatechange (eval at <anonymous> (https://manager.zboxapp.com/678875bundle.js:208:48), <anonymous>:30098:11)
From previous event:
    at enqueueUpdate (eval at <anonymous> (https://manager.zboxapp.com/678875bundle.js:96:48), <anonymous>:26:16)

```

Aquí la imagen
Google Chrome 

![screen shot 2016-06-01 at 12 11 04 pm](https://cloud.githubusercontent.com/assets/17553424/15716774/54c04230-27fa-11e6-9adb-ef3a719519a1.png)

**Comment by johuder33** [comment]
se cierra issue, debido a que es normal el max result.
